# action.yml
name: 'ImageMagick action'
description: 'Use ImageMagick in your repo as in your desktop'
branding:
  icon: 'upload'  
  color: 'yellow'
outputs:
  time:
    description: 'The time we greeted you'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
